(function(){
    //建立命名空间
    let namespace={};
    //渲染页
    namespace.Page=[
    '    <!-- 个人成就页组件 -->',
    '    <div style="width:640px;background-color: #ffffff;">',
    '        <!-- 导航栏 -->',
    '        <div style="width:640px;height:80px;background-color: rgb(255, 255, 255);align-items: center;display: flex;position: fixed;top:0px;border-bottom: 1px solid rgb(77, 160, 255);">',
    '            <!-- 返回按键 -->',
    '            <div class="hoverPointer" onclick="Slago.PageStack.pop()"',
    '                style="display: flex;height:100%;align-items: center;margin-left: 10px;">',
    '                <img src="./img/页面栈返回左箭头.png" style="height:40px;width:40px;">',
    '                <div style="height:100%;display: flex;align-items: center;margin-left: 3px;">',
    '                    <span style="font-size: 27px;color:#0066cc;">返回</span>',
    '                </div>',
    '            </div>',
    '            <!--导航栏字体栏-->',
    '            <div style="width:300px;height:100%;background-color:#ffffff;margin-left:66px;display:flex;align-items:center;justify-content: center;font-size:27px;">',
    '                发帖',
    '            </div>',
    '        </div>',
    '        <div style="height:80px;"></div>',
    '        <!-- 文字区域栏 -->',
    '        <div style="width:640px;margin-top: 10px;">',
    '            <textarea style="width: 600px;height:200px;outline: none;resize: none;color:rgb(36, 36, 36);padding: 10px;',
    '            background-color: #ffffff;font-size: 26px;margin-left: 10px;" placeholder="分享生活美好..."></textarea>',
    '        </div>',
    '        <!-- 图片添加与显示栏 -->',
    '        <div style="width:600px;margin-left: 20px;background-color: #ffffff;margin-top: 20px;">',
    '            <!-- 第一行 -->',
    '            <div style="height:220px;width:600px;background-color: rgb(255, 255, 255);display: flex;align-items: center;justify-content: space-around;">',
    '                <!-- 第一张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)" class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '                <!-- 第二张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)"  class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '                <!-- 第三张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)"  class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '            </div>',
    '            <!-- 第二行 -->',
    '            <div style="height:220px;width:600px;background-color: rgb(255, 255, 255);display: flex;align-items: center;justify-content: space-around;">',
    '                <!-- 第四张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)"  class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '                <!-- 第五张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)"  class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '                <!-- 第六张 -->',
    '                <div onclick="SlagoModel.PostUpPage.PostUpModel.click(this)"  class="hoverPointer" style="width:180px;height:180px;background-color: #fafafa;border-radius: 10px;',
    '                display: flex;justify-content: center;align-items: center;overflow: hidden;">',
    '                    <img src="./img/67.png" style="width:60px;height:60px;">',
    '                    <input type="file" accept="image/*" style="display: none;">',
    '                </div>',
    '            </div>',
    '        </div>',
    '        <!-- 提交按钮 -->',
    '        <div  style="width:640px;height:100px;background-color: rgb(255, 255, 255);margin-top: 40px;display: flex;align-items: center;">',
    '            <div onclick="SlagoModel.PostUpPage.PostUpModel.dataPost(this)" class="hoverPointer" style="width:120px;height:60px;background-color: #0066cc;',
    '            border-radius: 30px;margin-left: 455px;display: flex;',
    '            justify-content: center;align-items: center;',
    '            font-size: 24px;color:#ffffff;">',
    '                发布',
    '            </div>',
    '        </div>',
    '    </div>',
    ].join("");
    namespace.getModel=function(){
        return Slagolib.template.engin(this.Page,{});
    }
    namespace.show=function(){
        //创建页面,推入页面栈
        Slago.CreatePage(this.getModel());
    }
    //加入模块
    SlagoModel.PostUpPage.postupPage=namespace;
})();